version: '3.3'

services:

  bomber_app_dev:
    container_name: bomber_app_dev
    environment:
      - NODE_ENV="development"
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - "${BOMBERAPP_BIND_IP:-0.0.0.0:10001}:10001"
    # depends_on:
    #   - postgres
    volumes:
      - ".:/opt/app"
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge
